<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Eval Run: {{ $run->dataset_name }}</title>
<style>
@include('proofread::exports.partials.html-styles')
</style>
</head>
<body>
<div class="wrapper">
<h1>Eval Run: {{ $run->dataset_name }}</h1>

<p>
@if ($run->passed)
    <span class="badge badge-pass">Passed</span>
@else
    <span class="badge badge-fail">Failed</span>
@endif
</p>

<table>
<tr><th>Run ID</th><td><code>{{ $run->id }}</code></td></tr>
<tr><th>Dataset</th><td>{{ $run->dataset_name }}</td></tr>
@if ($datasetVersionChecksum !== null)
<tr><th>Version</th><td><code>{{ substr($datasetVersionChecksum, 0, 12) }}</code></td></tr>
@endif
<tr><th>Model</th><td>{{ $run->model ?? '—' }}</td></tr>
<tr><th>Commit</th><td><code>{{ $run->commit_sha ?? '—' }}</code></td></tr>
<tr><th>Created</th><td>{{ $run->created_at?->format('Y-m-d H:i:s') ?? '—' }} UTC</td></tr>
<tr><th>Duration</th><td>{{ number_format($run->duration_ms, 1) }} ms</td></tr>
</table>

<h2>Summary</h2>
<ul class="summary-list">
<li>Total cases: {{ $run->total_count }}</li>
<li>Passed: {{ $run->pass_count }}</li>
<li>Failed: {{ $run->fail_count }}</li>
<li>Errors: {{ $run->error_count }}</li>
<li>Pass rate: {{ number_format($run->passRate() * 100, 1) }}%</li>
@if ($run->total_cost_usd !== null)
<li>Total cost: ${{ number_format($run->total_cost_usd, 4) }}</li>
@endif
@if ($run->total_tokens_in !== null || $run->total_tokens_out !== null)
<li>Tokens in/out: {{ $run->total_tokens_in ?? '—' }} / {{ $run->total_tokens_out ?? '—' }}</li>
@endif
</ul>

<h2>Cases</h2>

@foreach ($results as $result)
<div class="case">
<div class="case-head">
@if ($result->error_class !== null)
    <span class="badge badge-warn">Error</span>
@elseif ($result->passed)
    <span class="badge badge-pass">Pass</span>
@else
    <span class="badge badge-fail">Fail</span>
@endif
<h3>Case {{ $result->case_index }}: {{ $result->case_name ?? 'unnamed' }}</h3>
</div>

<div class="case-meta muted">
{{ number_format($result->duration_ms, 1) }} ms
@if ($result->cost_usd !== null)
 · ${{ number_format($result->cost_usd, 4) }}
@endif
</div>

<h4>Input</h4>
<pre><code>{{ $truncate(is_string($result->input) ? $result->input : (string) json_encode($result->input, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE), 500) }}</code></pre>

<h4>Output</h4>
<pre><code>{{ $truncate((string) ($result->output ?? ''), 500) }}</code></pre>

@if ($result->error_class !== null)
<h4>Error</h4>
<div class="error-box">
<div class="error-class">{{ $result->error_class }}</div>
<div>{{ $truncate((string) ($result->error_message ?? ''), 500) }}</div>
</div>
@endif

<h4>Assertions</h4>
@php $assertions = is_array($result->assertion_results ?? null) ? $result->assertion_results : []; @endphp
@if ($assertions === [])
<p class="muted">No assertions recorded.</p>
@else
<ul class="assertion-list">
@foreach ($assertions as $assertion)
@php
    $name = is_array($assertion) && isset($assertion['name']) ? (string) $assertion['name'] : 'unknown';
    $passed = is_array($assertion) && (bool) ($assertion['passed'] ?? false);
    $reason = is_array($assertion) && isset($assertion['reason']) ? (string) $assertion['reason'] : '';
@endphp
<li>
@if ($passed)
    <span class="badge badge-pass">Pass</span>
@else
    <span class="badge badge-fail">Fail</span>
@endif
<span class="assertion-name">{{ $name }}</span>
@if ($reason !== '')
    <span class="muted">{{ $truncate($reason, 200) }}</span>
@endif
</li>
@endforeach
</ul>
@endif
</div>
@endforeach

<footer>
Generated by Proofread {{ $proofreadVersion }} at {{ $generatedAt }}
</footer>
</div>
</body>
</html>
