# Eval Run: {!! $run->dataset_name !!}

**Status:** {{ $run->passed ? 'PASSED' : 'FAILED' }}

| Field | Value |
|---|---|
| Run ID | `{!! $run->id !!}` |
| Dataset | {!! $run->dataset_name !!} |
@if ($datasetVersionChecksum !== null)
| Version | `{!! substr($datasetVersionChecksum, 0, 12) !!}` |
@endif
| Model | {!! $run->model ?? '—' !!} |
| Commit | `{!! $run->commit_sha ?? '—' !!}` |
| Created | {!! $run->created_at?->format('Y-m-d H:i:s') ?? '—' !!} UTC |
| Duration | {{ number_format($run->duration_ms, 1) }} ms |

## Summary

- Total cases: {{ $run->total_count }}
- Passed: {{ $run->pass_count }}
- Failed: {{ $run->fail_count }}
- Errors: {{ $run->error_count }}
- Pass rate: {{ number_format($run->passRate() * 100, 1) }}%
@if ($run->total_cost_usd !== null)
- Total cost: ${{ number_format($run->total_cost_usd, 4) }}
@endif
@if ($run->total_tokens_in !== null || $run->total_tokens_out !== null)
- Tokens in/out: {{ $run->total_tokens_in ?? '—' }} / {{ $run->total_tokens_out ?? '—' }}
@endif

## Cases

@foreach ($results as $result)
### Case {{ $result->case_index }}: {!! $result->case_name ?? 'unnamed' !!}

@php
    if ($result->error_class !== null) {
        $statusLabel = 'ERROR';
    } elseif ($result->passed) {
        $statusLabel = 'PASS';
    } else {
        $statusLabel = 'FAIL';
    }
    $costSuffix = $result->cost_usd !== null
        ? ' · **Cost:** $'.number_format($result->cost_usd, 4)
        : '';
    $inputText = is_string($result->input)
        ? $result->input
        : (string) json_encode($result->input, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    $outputText = (string) ($result->output ?? '');
@endphp
**Status:** {{ $statusLabel }} · **Duration:** {{ number_format($result->duration_ms, 1) }}ms{!! $costSuffix !!}

**Input:**

```
{!! $truncate($inputText, 500) !!}
```

**Output:**

```
{!! $truncate($outputText, 500) !!}
```

@if ($result->error_class !== null)
**Error:** `{!! $result->error_class !!}` — {!! $truncate((string) ($result->error_message ?? ''), 500) !!}
@endif

**Assertions:**
@php $assertions = is_array($result->assertion_results ?? null) ? $result->assertion_results : []; @endphp
@if ($assertions === [])
- _No assertions recorded._
@else
@foreach ($assertions as $assertion)
@php
    $name = is_array($assertion) && isset($assertion['name']) ? (string) $assertion['name'] : 'unknown';
    $passed = is_array($assertion) && (bool) ($assertion['passed'] ?? false);
    $reason = is_array($assertion) && isset($assertion['reason']) ? (string) $assertion['reason'] : '';
    $reasonSuffix = $reason !== '' ? ' — '.$truncate($reason, 200) : '';
@endphp
- `{!! $name !!}` {{ $passed ? '[PASS]' : '[FAIL]' }}{!! $reasonSuffix !!}
@endforeach
@endif

---

@endforeach

_Generated by Proofread {!! $proofreadVersion !!} at {!! $generatedAt !!}_
