<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Eval Comparison: {{ $comparison->name }}</title>
<style>
@include('proofread::exports.partials.html-styles')
.winners-grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 12px;
    margin: 12px 0;
}
.winner-card {
    border: 1px solid #d0d7de;
    border-radius: 6px;
    padding: 12px;
    background: #f6f8fa;
}
.winner-card h3 {
    margin: 0 0 6px 0;
    font-size: 13px;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #656d76;
}
.winner-label {
    font-family: SFMono-Regular, Consolas, monospace;
    font-size: 14px;
    font-weight: 600;
}
.winner-metric {
    color: #1a7f37;
    font-weight: 600;
    font-size: 16px;
}
.matrix-table td.cell-pass { background: #dafbe1; color: #1a7f37; font-weight: 600; }
.matrix-table td.cell-fail { background: #ffebe9; color: #cf222e; font-weight: 600; }
.matrix-table td.cell-error { background: #fff8c5; color: #9a6700; font-weight: 600; }
.matrix-table td.cell-case { font-family: SFMono-Regular, Consolas, monospace; font-size: 12px; text-align: left; }
.matrix-table th, .matrix-table td { text-align: center; }
</style>
</head>
<body>
<div class="wrapper">
<h1>Eval Comparison: {{ $comparison->name }}</h1>

<p>
@php $allPassed = $comparison->passed_runs === $comparison->total_runs && $comparison->total_runs > 0; @endphp
@if ($allPassed)
    <span class="badge badge-pass">Passed</span>
@else
    <span class="badge badge-fail">Failed</span>
@endif
</p>

<table>
<tr><th>Comparison ID</th><td><code>{{ $comparison->id }}</code></td></tr>
<tr><th>Dataset</th><td>{{ $comparison->dataset_name }}</td></tr>
@if ($datasetVersionChecksum !== null)
<tr><th>Version</th><td><code>{{ substr($datasetVersionChecksum, 0, 12) }}</code></td></tr>
@endif
<tr><th>Subjects</th><td>{{ implode(', ', $comparison->subject_labels) }}</td></tr>
<tr><th>Commit</th><td><code>{{ $comparison->commit_sha ?? '—' }}</code></td></tr>
<tr><th>Created</th><td>{{ $comparison->created_at?->format('Y-m-d H:i:s') ?? '—' }} UTC</td></tr>
<tr><th>Duration</th><td>{{ number_format((float) $comparison->duration_ms, 1) }} ms</td></tr>
</table>

<h2>Summary</h2>
<ul class="summary-list">
<li>Total runs: {{ $comparison->total_runs }}</li>
<li>Passed: {{ $comparison->passed_runs }}</li>
<li>Failed: {{ $comparison->failed_runs }}</li>
@if ($comparison->total_cost_usd !== null)
<li>Total cost: ${{ number_format((float) $comparison->total_cost_usd, 4) }}</li>
@endif
</ul>

<h2>Winners</h2>
<div class="winners-grid">
@if ($bestByPassRate !== null)
<div class="winner-card">
<h3>Best pass rate</h3>
<div class="winner-label">{{ $bestByPassRate->subject_label }}</div>
<div class="winner-metric">{{ number_format(($bestByPassRate->pass_count / max(1, $bestByPassRate->total_count)) * 100, 1) }}%</div>
</div>
@endif
@if ($cheapest !== null)
<div class="winner-card">
<h3>Cheapest</h3>
<div class="winner-label">{{ $cheapest->subject_label }}</div>
<div class="winner-metric">${{ number_format((float) $cheapest->total_cost_usd, 4) }}</div>
</div>
@endif
@if ($fastest !== null)
<div class="winner-card">
<h3>Fastest</h3>
<div class="winner-label">{{ $fastest->subject_label }}</div>
<div class="winner-metric">{{ number_format((float) $fastest->duration_ms, 1) }} ms</div>
</div>
@endif
</div>

<h2>Matrix</h2>
<table class="matrix-table">
<thead>
<tr>
<th>Case</th>
@foreach ($comparison->subject_labels as $label)
<th>{{ $label }}</th>
@endforeach
</tr>
</thead>
<tbody>
@foreach ($matrixRows as $row)
<tr>
<td class="cell-case">{{ $row['name'] }}</td>
@foreach ($row['cells'] as $cell)
@php
    if ($cell['error']) {
        $cls = 'cell-error';
        $label = 'ERR';
    } elseif ($cell['passed']) {
        $cls = 'cell-pass';
        $label = 'PASS';
    } else {
        $cls = 'cell-fail';
        $label = 'FAIL';
    }
@endphp
<td class="{{ $cls }}">{{ $label }}</td>
@endforeach
</tr>
@endforeach
</tbody>
</table>

<h2>Per-subject stats</h2>
@foreach ($comparison->runs as $run)
<div class="case">
<div class="case-head">
@if ($run->passed)
    <span class="badge badge-pass">Pass</span>
@else
    <span class="badge badge-fail">Fail</span>
@endif
<h3>{{ $run->subject_label }}</h3>
</div>
<ul class="summary-list">
<li>Pass rate: {{ number_format(($run->pass_count / max(1, $run->total_count)) * 100, 1) }}%</li>
<li>Duration: {{ number_format((float) $run->duration_ms, 1) }} ms</li>
@if ($run->total_cost_usd !== null)
<li>Cost: ${{ number_format((float) $run->total_cost_usd, 4) }}</li>
@endif
@if ($run->total_tokens_in !== null || $run->total_tokens_out !== null)
<li>Tokens in/out: {{ $run->total_tokens_in ?? '—' }} / {{ $run->total_tokens_out ?? '—' }}</li>
@endif
</ul>
</div>
@endforeach

<footer>
Generated by Proofread {{ $proofreadVersion }} at {{ $generatedAt }}
</footer>
</div>
</body>
</html>
