# Eval Comparison: {!! $comparison->name !!}

**Status:** {{ $comparison->passed_runs === $comparison->total_runs && $comparison->total_runs > 0 ? 'PASSED' : 'FAILED' }}

| Field | Value |
|---|---|
| Comparison ID | `{!! $comparison->id !!}` |
| Dataset | {!! $comparison->dataset_name !!} |
@if ($datasetVersionChecksum !== null)
| Version | `{!! substr($datasetVersionChecksum, 0, 12) !!}` |
@endif
| Subjects | {!! implode(', ', $comparison->subject_labels) !!} |
| Commit | `{!! $comparison->commit_sha ?? '—' !!}` |
| Created | {!! $comparison->created_at?->format('Y-m-d H:i:s') ?? '—' !!} UTC |
| Duration | {{ number_format((float) $comparison->duration_ms, 1) }} ms |

## Summary

- Total runs: {{ $comparison->total_runs }}
- Passed: {{ $comparison->passed_runs }}
- Failed: {{ $comparison->failed_runs }}
@if ($comparison->total_cost_usd !== null)
- Total cost: ${{ number_format((float) $comparison->total_cost_usd, 4) }}
@endif

## Winners

| Category | Subject | Metric |
|---|---|---|
@if ($bestByPassRate !== null)
| Best pass rate | `{!! $bestByPassRate->subject_label !!}` | {{ number_format(($bestByPassRate->pass_count / max(1, $bestByPassRate->total_count)) * 100, 1) }}% |
@endif
@if ($cheapest !== null)
| Cheapest | `{!! $cheapest->subject_label !!}` | ${{ number_format((float) $cheapest->total_cost_usd, 4) }} |
@endif
@if ($fastest !== null)
| Fastest | `{!! $fastest->subject_label !!}` | {{ number_format((float) $fastest->duration_ms, 1) }} ms |
@endif

## Matrix

| Case |@foreach ($comparison->subject_labels as $label) {!! $label !!} |@endforeach

|---|@foreach ($comparison->subject_labels as $label)---|@endforeach

@foreach ($matrixRows as $row)
| {!! $row['name'] !!} |@foreach ($row['cells'] as $cell) {{ $cell['error'] ? 'ERR' : ($cell['passed'] ? 'PASS' : 'FAIL') }} |@endforeach

@endforeach

## Per-subject stats

@foreach ($comparison->runs as $run)
### {!! $run->subject_label !!}

- Pass rate: {{ number_format(($run->pass_count / max(1, $run->total_count)) * 100, 1) }}%
- Duration: {{ number_format((float) $run->duration_ms, 1) }} ms
@if ($run->total_cost_usd !== null)
- Cost: ${{ number_format((float) $run->total_cost_usd, 4) }}
@endif
@if ($run->total_tokens_in !== null || $run->total_tokens_out !== null)
- Tokens in/out: {{ $run->total_tokens_in ?? '—' }} / {{ $run->total_tokens_out ?? '—' }}
@endif

@endforeach

_Generated by Proofread {!! $proofreadVersion !!} at {!! $generatedAt !!}_
